services:
  caddy:
    image: caddy:2
    container_name: borevitz-caddy
    # depends_on: [frontend, backend]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ops/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      DOMAIN: http://130.56.246.157   # e.g., app.example.com
    restart: always
    networks:
      - default
      - edge

volumes:
  caddy_data:
  caddy_config:

networks:
  edge:
    external: true
